import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { FormEvent, useContext, useState } from 'react'
import { AuthContext } from '../contexts/AuthContext'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')

  const { signIn, isAuthenticated } = useContext(AuthContext)

  async function handleSubmit(e: FormEvent) {
    e.preventDefault()
    const data = {
      email,
      password,
    }

    await signIn(data)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className={styles.form} onSubmit={handleSubmit}>
        <input type="email" placeholder='email' value={email} onChange={e => setEmail(e.target.value)} />
        <input type="password" placeholder='password' value={password} onChange={e => setPassword(e.target.value)} />
        <button type='submit'>Entrar</button>
      </form>
    </div>
  )
}

export default Home


export const getServerSideProps: GetServerSideProps = async (ctx) => {
  console.log(ctx.req.cookies)
  return {
    props: {}
  }
}